import type { MiniGame, NormalizedLandmark, PlayersTracking } from '../types';
type DancePose = { name: string; angles: [number, number, number, number, number, number] };
type Round = { best: number };
const COLORS = ['#60a5fa', '#f472b6'] as const;
const POSES: DancePose[] = [{ name: 'T pozu', angles: [90, 90, 90, 90, 175, 175] }, { name: 'Eller yukarı', angles: [165, 165, 35, 35, 175, 175] }, { name: 'Çömelmiş poz', angles: [90, 90, 90, 90, 85, 85] }, { name: 'Tek kol yukarı', angles: [165, 90, 35, 90, 175, 175] }];
export class DanceMimic implements MiniGame {
  readonly tracking = 'pose' as const; readonly needs = 'pose' as const; readonly duration = 24;
  private width = 0; private height = 0; private elapsed = 0; private round = 0; private rounds: [Round, Round] = [{ best: 0 }, { best: 0 }]; private scores: [number, number] = [0, 0]; private audio: AudioContext | null = null;
  start(width: number, height: number): void { this.width = width; this.height = height; this.elapsed = 0; this.round = 0; this.scores = [0, 0]; this.rounds = [{ best: 0 }, { best: 0 }]; }
  update(dt: number, players: PlayersTracking): void { const next = Math.min(3, Math.floor(this.elapsed / 6)); if (next !== this.round) { this.scores[0] += Math.round(this.rounds[0].best * 10); this.scores[1] += Math.round(this.rounds[1].best * 10); this.round = next; this.rounds = [{ best: 0 }, { best: 0 }]; this.beep(); } this.elapsed += dt; players.forEach((player, i) => { const pose = player.pose?.pose; if (!pose) return; const result = this.similarity(pose, POSES[this.round].angles); if (result.reliable) this.rounds[i].best = Math.max(this.rounds[i].best, result.score); }); }
  draw(context: CanvasRenderingContext2D): void { const pose = POSES[this.round]; context.save(); context.textAlign = 'center'; context.fillStyle = '#fff'; context.font = `700 ${Math.max(14, this.width / 42)}px system-ui`; context.fillText(`Dans Taklidi • ${pose.name}`, this.width / 2, Math.max(28, this.height * .11)); context.font = `600 ${Math.max(13, this.width / 48)}px system-ui`; context.fillText(`Tur süresi: ${Math.max(0, Math.ceil(6 - (this.elapsed % 6)))} sn`, this.width / 2, this.height * .17); this.rounds.forEach((r, i) => { const x = i ? this.width * .75 : this.width * .25; context.fillStyle = COLORS[i]; context.fillText(`Oyuncu ${i + 1}: ${Math.round(r.best * 100)}% • ${this.scores[i]}`, x, this.height * .84); context.strokeStyle = '#ffffff55'; context.strokeRect(x - this.width * .16, this.height * .87, this.width * .32, 12); context.fillRect(x - this.width * .16, this.height * .87, this.width * .32 * r.best, 12); }); context.restore(); }
  getScores(): [number, number] { const final: [number, number] = [...this.scores]; if (this.elapsed >= 24) { final[0] += Math.round(this.rounds[0].best * 10); final[1] += Math.round(this.rounds[1].best * 10); } return final; }
  private similarity(pose: NormalizedLandmark[], target: DancePose['angles']): { score: number; reliable: boolean } { const points: [number, number, number][] = [[11, 13, 15], [12, 14, 16], [11, 23, 25], [12, 24, 26], [23, 25, 27], [24, 26, 28]]; if (points.some((t) => t.some((i) => !this.good(pose[i])))) return { score: 0, reliable: false }; const values = points.map(([a, b, c]) => this.angle(pose[a], pose[b], pose[c])); return { score: values.reduce((sum, value, i) => sum + Math.max(0, 1 - Math.abs(value - target[i]) / 180), 0) / values.length, reliable: true }; }
  private good(point: NormalizedLandmark | undefined): boolean { return Boolean(point && (point.visibility ?? point.presence ?? 1) >= .55); }
  private angle(a: NormalizedLandmark, b: NormalizedLandmark, c: NormalizedLandmark): number { const ab = Math.atan2(a.y - b.y, a.x - b.x), cb = Math.atan2(c.y - b.y, c.x - b.x); let d = Math.abs((ab - cb) * 180 / Math.PI); return d > 180 ? 360 - d : d; }
  private beep(): void { try { this.audio ??= new AudioContext(); const o = this.audio.createOscillator(); const g = this.audio.createGain(); o.frequency.value = 650; g.gain.value = .03; o.connect(g).connect(this.audio.destination); o.start(); o.stop(this.audio.currentTime + .08); } catch { /* ses yoksa oyun devam eder */ } }
}
